- title: Adesivos
  brief: Divulgar sua marca ou produto de forma pr&aacute;tica e eficiente.
  description: Atrav&eacute;s de adesivos personalizados, as empresas podem divulgar sua marca ou produto de forma pr&aacute;tica e eficiente.
  icon: <i class="fa fa-file" aria-hidden="true"></i>

- title: Display
  brief: Displays para decorar ambientes, sinalizar eventos ou divulgar campanhas e promo&ccedil;ões.
  description: A impress&atilde;o digital permite a confec&ccedil;&atilde;o de displays em diversos formatos, tamanhos e materiais. A Maxsigns est&aacute; apta a criar e produzir displays para decorar ambientes, sinalizar eventos ou divulgar campanhas e promo&ccedil;ões.
  icon: <i class="fa fa-lightbulb-o" aria-hidden="true"></i>

- title: Banner
  brief: Banners impressos em lona e nas mais diversas m&iacute;dias papel, adesivo e tecido.
  description: A Maxsigns produz banners impressos em lona e nas mais diversas m&iacute;dias papel, adesivo, tecido, corte em fl&acirc;mula, podendo variar de tamanho, material e acabamento.
  icon: <i class="fa fa-flag" aria-hidden="true"></i>

- title: Envelopamento de frota
  brief: Transforme os ve&iacute;culos em excelentes meios de divulga&ccedil;&atilde;o permanente de sua empresa.
  description: O envelopamento de ve&iacute;culos &eacute; um recurso muito utlizado por empresas que buscam a padroniza&ccedil;&atilde;o e a diferencia&ccedil;&atilde;o de sua frota, transformando os ve&iacute;culos em excelentes meios de divulga&ccedil;&atilde;o permanente de sua empresa.
  icon: <i class="fa fa-truck" aria-hidden="true"></i>

- title: Backlight
  brief: Iluminar sua marca ou o seu produto em divulga&ccedil;&atilde;o ganha ainda mais destaque.
  description: Ilumine sua marca e o seu neg&oacute;cio. Atrav&eacute;s de backlights, totens e testeiras com retro ilumina&ccedil;&atilde;o que passa por uma lona translúcida, a sua marca ou o seu produto em divulga&ccedil;&atilde;o ganham ainda mais destaque.
  icon: <i class="fa fa-globe" aria-hidden="true"></i>

- title: Frontlight
  brief: Um simples banner pode ganhar destaque ainda maior com a ilumina&ccedil;&atilde;o adequada aplicada &agrave; sua frente.
  description: Um simples banner pode ganhar destaque ainda maior com a ilumina&ccedil;&atilde;o adequada aplicada &agrave; sua frente, para sinalizar e real&ccedil;ar a mensagem nele impressa. A sinaliza&ccedil;&atilde;o atrav&eacute;s de um letreiro bem iluminado permite uma comunica&ccedil;&atilde;o muito mais eficiente. Trabalhamos com materiais de excelente qualidade e impress&atilde;o de &oacute;tima defini&ccedil;&atilde;o.
  icon: <i class="fa fa-bolt" aria-hidden="true"></i>
