- title: Manuten&ccedil;&atilde;o
  brief: Manuten&ccedil;&atilde;o de totens, letreiros e banners.
  description: Se a sua empresa necessita de manuten&ccedil;&atilde;o na sua comunica&ccedil;&atilde;o visual, pe&ccedil;a um or&ccedil;amento gr&aacute;tis.
  icon: <i class="fa fa-file" aria-hidden="true"></i>

- title: Retirada
  brief: Retirada de totens e letreiros.
  description: A Maxsigns faz a retirada de totens e letreiros para renova&ccedil;&atilde;o ou manuten&ccedil;&atilde;o.
  icon: <i class="fa fa-file" aria-hidden="true"></i>

- title: Instala&ccedil;&atilde;o
  brief: Instala&ccedil;&atilde;o de totens, letreiros e banners.
  description: Se voc&ecirc; precisa de uma instalar seu letreiro, a Maxsigns tem profissionais capacitados para qualquer tipo de instala&ccedil;&atilde;o.
  icon: <i class="fa fa-file" aria-hidden="true"></i>
